### ISSUE TITLE
How to get tokens

### ISSUE THREAD

**Issue by Jzarecta** [juanpabloaj/slacker-cli#22]
Sorry I am not a slack power user nor I want to be, so I want to use your software so I dont have to constantly login into slack, however I need a token, anyway to learn how to get it. Do I need to build a bot on a slack channel for it?

**Comment by juanpabloaj** [comment]
https://api.slack.com/docs/oauth-test-tokens

to get a token I suppose you need be part of a team

**Comment by hugovk** [comment]
Another way is to create a bot user and use its token:

https://my.slack.com/apps/A0F7YS25R-bots
