### ISSUE TITLE
-u send message to user

### ISSUE THREAD

**Issue by juanpabloaj** [juanpabloaj/slacker-cli#3]

**Comment by davidyen1124** [comment]
If we know the user id, then we can send message to user.
We can use `slack.users.list().body` then find user name in the body, and get his/her user id.

**Comment by juanpabloaj** [comment]
yes, I made something similar to get the channel id with the channel name 

https://github.com/juanpabloaj/slacker-cli/blob/1a0e9dcb0c5e17caf53b79881c48b7fb6a2b766d/slacker_cli/__init__.py#L20

**Comment by juanpabloaj** [comment]
I prefer

     -c channel
     -u user 

because I guess it's easier to remember.

**Comment by juanpabloaj** [comment]
complete in 2472682063a47037119037cd7af069ffa286bab4
